export var name_to_code = {
    'Afghanistan': 'AFG',
    'Angola': 'AGO',
    'Albania': 'ALB',
    'United Arab Emirates': 'ARE',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'French Southern and Antarctic Lands': 'ATF',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Burundi': 'BDI',
    'Belgium': 'BEL',
    'Benin': 'BEN',
    'Burkina Faso': 'BFA',
    'Bangladesh': 'BGD',
    'Bulgaria': 'BGR',
    'The Bahamas': 'BHS',
    'Bosnia and Herzegovina': 'BIH',
    'Belarus': 'BLR',
    'Belize': 'BLZ',
    'Bermuda': 'BMU',
    'Bolivia': 'BOL',
    'Brazil': 'BRA',
    'Brunei': 'BRN',
    'Bhutan': 'BTN',
    'Botswana': 'BWA',
    'Central African Republic': 'CAF',
    'Canada': 'CAN',
    'Switzerland': 'CHE',
    'Chile': 'CHL',
    'China': 'CHN',
    'Ivory Coast': 'CIV',
    'Cameroon': 'CMR',
    'Democratic Republic of the Congo': 'COD',
    'Republic of the Congo': 'COG',
    'Colombia': 'COL',
    'Costa Rica': 'CRI',
    'Cuba': 'CUB',
    'Northern Cyprus': 'CYP',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Germany': 'DEU',
    'Djibouti': 'DJI',
    'Denmark': 'DNK',
    'Dominican Republic': 'DOM',
    'Algeria': 'DZA',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'Eritrea': 'ERI',
    'Spain': 'ESP',
    'Estonia': 'EST',
    'Ethiopia': 'ETH',
    'Finland': 'FIN',
    'Fiji': 'FJI',
    'Falkland Islands': 'FLK',
    'France': 'FRA',
    'Gabon': 'GAB',
    'United Kingdom': 'GBR',
    'Georgia': 'GEO',
    'Ghana': 'GHA',
    'Guinea': 'GIN',
    'Gambia': 'GMB',
    'Guinea Bissau': 'GNB',
    'Equatorial Guinea': 'GNQ',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Guatemala': 'GTM',
    'French Guiana': 'GUF',
    'Guyana': 'GUY',
    'Honduras': 'HND',
    'Croatia': 'HRV',
    'Haiti': 'HTI',
    'Hungary': 'HUN',
    'Indonesia': 'INA',
    'India': 'IND',
    'Ireland': 'IRL',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Jordan': 'JOR',
    'Japan': 'JPN',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kyrgyzstan': 'KGZ',
    'Cambodia': 'KHM',
    'South Korea': 'KOR',
    'Kosovo': false,
    'Kuwait': 'KWT',
    'Laos': 'LAO',
    'Lebanon': 'LBN',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Sri Lanka': 'LKA',
    'Lesotho': 'LSO',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Latvia': 'LVA',
    'Morocco': 'MAR',
    'Moldova': 'MDA',
    'Madagascar': 'MDG',
    'Mexico': 'MEX',
    'Macedonia': 'MKD',
    'Mali': 'MLI',
    'Myanmar': 'MMR',
    'Montenegro': 'MNE',
    'Mongolia': 'MNG',
    'Mozambique': 'MOZ',
    'Mauritania': 'MRT',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Namibia': 'NAM',
    'New Caledonia': 'NCL',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Nicaragua': 'NIC',
    'Netherlands': 'NLD',
    'Norway': 'NOR',
    'Nepal': 'NPL',
    'New Zealand': 'NZL',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Panama': 'PAN',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Papua New Guinea': 'PNG',
    'Poland': 'POL',
    'Puerto Rico': 'PRI',
    'North Korea': 'PRK',
    'Portugal': 'PRT',
    'Paraguay': 'PRY',
    'Qatar': 'QAT',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Rwanda': 'RWA',
    'Western Sahara': 'ESH',
    'Saudi Arabia': 'SAU',
    'Sudan': 'SDN',
    'South Sudan': 'SSD',
    'Senegal': 'SEN',
    'Solomon Islands': 'SLB',
    'Sierra Leone': 'SLE',
    'El Salvador': 'SLV',
    'Somaliland': false,
    'Somalia': 'SOM',
    'Republic of Serbia': 'SRB',
    'Suriname': 'SUR',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Sweden': 'SWE',
    'Swaziland': 'SWZ',
    'Syria': 'SYR',
    'Chad': 'TCD',
    'Togo': 'TGO',
    'Thailand': 'THA',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'East Timor': 'TLS',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'United Republic of Tanzania': 'TZA',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'Uruguay': 'URY',
    'America': 'USA',
    'Uzbekistan': 'UZB',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Vanuatu': 'VUT',
    'West Bank': false,
    'Yemen': 'YEM',
    'South Africa': 'ZAF',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE'
    };   

export var __tw = {
    "AF": "AFG",
    "AL": "ALB",
    "DZ": "ALG",
    "AD": "AND",
    "AO": "ANG",
    "AG": "ANT",
    "AR": "ARG",
    "AM": "ARM",
    "AU": "AUS",
    "AT": "AUT",
    "AZ": "AZE",
    "BS": "BAH",
    "BD": "BAN",
    "BB": "BAR",
    "BE": "BEL",
    "BJ": "BEN",
    "BI": "BDI",
    "BT": "BHU",
    "BZ": "BIZ",
    "BY": "BLR",
    "BO": "BOL",
    "BW": "BOT",
    "BR": "BRA",
    "BH": "BRN",
    "BN": "BRU",
    "BG": "BUL",
    "BF": "BUR",
    "CF": "CAF",
    "KH": "CAM",
    "CA": "CAN",
    "TD": "CHA",
    "CG": "CGO",
    "CL": "CHI",
    "CN": "CHN",
    "CI": "CIV",
    "CM": "CMR",
    "CD": "COD",
    "CO": "COL",
    "KM": "COM",
    "CV": "CPV",
    "CR": "CRC",
    "HR": "CRO",
    "CU": "CUB",
    "CY": "CYP",
    "CZ": "CZE",
    "DK": "DEN",
    "DJ": "DJI",
    "DM": "DMA",
    "DO": "DOM",
    "EC": "ECU",
    "EG": "EGY",
    "ER": "ERI",
    "SV": "ESA",
    "ES": "ESP",
    "EE": "EST",
    "ET": "ETH",
    "FJ": "FIJ",
    "FI": "FIN",
    "FM": "FSM",
    "FR": "FRA",
    "GA": "GAB",
    "GM": "GAM",
    "UK": "GBR",
    "GE": "GEO",
    "GQ": "GEQ",
    "DE": "GER",
    "GH": "GHA",
    "GW": "GNB",
    "GR": "GRE",
    "GD": "GRN",
    "GT": "GUA",
    "GN": "GUI",
    "GY": "GUY",
    "HT": "HAI",
    "HN": "HON",
    "HU": "HUN",
    "IN": "IND",
    "ID": "INA",
    "IR": "IRI",
    "IE": "IRL",
    "IQ": "IRQ",
    "IS": "ISL",
    "IL": "ISR",
    "IT": "ITA",
    "JM": "JAM",
    "JO": "JOR",
    "JP": "JPN",
    "KZ": "KAZ",
    "KE": "KEN",
    "KG": "KGZ",
    "KI": "KIR",
    "KR": "KOR",
    "SA": "KSA",
    "KW": "KUW",
    "LA": "LAO",
    "LV": "LAT",
    "LY": "LBA",
    "LR": "LBR",
    "LC": "LCA",
    "LS": "LES",
    "LB": "LIB",
    "LI": "LIE",
    "LT": "LTU",
    "LU": "LUX",
    "MG": "MAD",
    "MA": "MAR",
    "MY": "MAS",
    "MW": "MAW",
    "MD": "MDA",
    "MV": "MDV",
    "MX": "MEX",
    "MN": "MGL",
    "MK": "MKD",
    "ML": "MLI",
    "MT": "MLT",
    "MC": "MON",
    "MZ": "MOZ",
    "MU": "MRI",
    "MR": "MTN",
    "MM": "MYA",
    "NA": "NAM",
    "NP": "NEP",
    "NI": "NCA",
    "NL": "NED",
    "NG": "NGR",
    "NE": "NIG",
    "NO": "NOR",
    "NR": "NRU",
    "NZ": "NZL",
    "OM": "OMA",
    "PK": "PAK",
    "PA": "PAN",
    "PY": "PAR",
    "PE": "PER",
    "PH": "PHI",
    "PS": "PLE",
    "PW": "PLW",
    "PG": "PNG",
    "PL": "POL",
    "PT": "POR",
    "KP": "PRK",
    "QA": "QAT",
    "MH": "RMI",
    "RO": "ROM",
    "ZA": "RSA",
    "RU": "RUS",
    "RW": "RWA",
    "WS": "SAM",
    "RS": "SCG",
    "SN": "SEN",
    "SC": "SEY",
    "SG": "SIN",
    "KN": "SKN",
    "SL": "SLE",
    "SI": "SLO",
    "SM": "SMR",
    "SB": "SOL",
    "SO": "SOM",
    "LK": "SRI",
    "ST": "STP",
    "SD": "SUD",
    "CH": "SUI",
    "SR": "SUR",
    "SK": "SVK",
    "SZ": "SWZ",
    "SE": "SWE",
    "SY": "SYR",
    "TZ": "TAN",
    "TO": "TGA",
    "TH": "THA",
    "TJ": "TJK",
    "TM": "TKM",
    "TL": "TLS",
    "TG": "TOG",
    "TT": "TRI",
    "TN": "TUN",
    "TR": "TUR",
    "TV": "TUV",
    "AE": "UAE",
    "UG": "UGA",
    "UA": "UKR",
    "UY": "URU",
    "US": "USA",
    "UZ": "UZB",
    "VU": "VAN",
    "VA": "VAT",
    "VE": "VEN",
    "VN": "VIE",
    "VC": "VIN",
    "YE": "YEM",
    "ZM": "ZAM",
    "ZW": "ZIM"
};
