import {_flipObject} from './index';
import _fromPairs from 'lodash/fromPairs'; //


// export var __tw = {
//     "AF": "AFG",
//     "AL": "ALB",
//     "DZ": "ALG",
//     "AD": "AND",
//     "AO": "ANG",
//     "AG": "ANT",
//     "AR": "ARG",
//     "AM": "ARM",
//     "AU": "AUS",
//     "AT": "AUT",
//     "AZ": "AZE",
//     "BS": "BAH",
//     "BD": "BAN",
//     "BB": "BAR",
//     "BE": "BEL",
//     "BJ": "BEN",
//     "BI": "BDI",
//     "BT": "BHU",
//     "BZ": "BIZ",
//     "BY": "BLR",
//     "BO": "BOL",
//     "BW": "BOT",
//     "BR": "BRA",
//     "BH": "BRN",
//     "BN": "BRU",
//     "BG": "BUL",
//     "BF": "BUR",
//     "CF": "CAF",
//     "KH": "CAM",
//     "CA": "CAN",
//     "TD": "CHA",
//     "CG": "CGO",
//     "CL": "CHI",
//     "CN": "CHN",
//     "CI": "CIV",
//     "CM": "CMR",
//     "CD": "COD",
//     "CO": "COL",
//     "KM": "COM",
//     "CV": "CPV",
//     "CR": "CRC",
//     "HR": "CRO",
//     "CU": "CUB",
//     "CY": "CYP",
//     "CZ": "CZE",
//     "DK": "DEN",
//     "DJ": "DJI",
//     "DM": "DMA",
//     "DO": "DOM",
//     "EC": "ECU",
//     "EG": "EGY",
//     "ER": "ERI",
//     "SV": "ESA",
//     "ES": "ESP",
//     "EE": "EST",
//     "ET": "ETH",
//     "FJ": "FIJ",
//     "FI": "FIN",
//     "FM": "FSM",
//     "FR": "FRA",
//     "GA": "GAB",
//     "GM": "GAM",
//     "UK": "GBR",
//     "GE": "GEO",
//     "GQ": "GEQ",
//     "DE": "GER",
//     "GH": "GHA",
//     "GW": "GNB",
//     "GR": "GRE",
//     "GD": "GRN",
//     "GT": "GUA",
//     "GN": "GUI",
//     "GY": "GUY",
//     "HT": "HAI",
//     "HN": "HON",
//     "HU": "HUN",
//     "IN": "IND",
//     "ID": "INA",
//     "IR": "IRI",
//     "IE": "IRL",
//     "IQ": "IRQ",
//     "IS": "ISL",
//     "IL": "ISR",
//     "IT": "ITA",
//     "JM": "JAM",
//     "JO": "JOR",
//     "JP": "JPN",
//     "KZ": "KAZ",
//     "KE": "KEN",
//     "KG": "KGZ",
//     "KI": "KIR",
//     "KR": "KOR",
//     "SA": "KSA",
//     "KW": "KUW",
//     "LA": "LAO",
//     "LV": "LAT",
//     "LY": "LBA",
//     "LR": "LBR",
//     "LC": "LCA",
//     "LS": "LES",
//     "LB": "LIB",
//     "LI": "LIE",
//     "LT": "LTU",
//     "LU": "LUX",
//     "MG": "MAD",
//     "MA": "MAR",
//     "MY": "MAS",
//     "MW": "MAW",
//     "MD": "MDA",
//     "MV": "MDV",
//     "MX": "MEX",
//     "MN": "MGL",
//     "MK": "MKD",
//     "ML": "MLI",
//     "MT": "MLT",
//     "MC": "MON",
//     "MZ": "MOZ",
//     "MU": "MRI",
//     "MR": "MTN",
//     "MM": "MYA",
//     "NA": "NAM",
//     "NP": "NEP",
//     "NI": "NCA",
//     "NL": "NED",
//     "NG": "NGR",
//     "NE": "NIG",
//     "NO": "NOR",
//     "NR": "NRU",
//     "NZ": "NZL",
//     "OM": "OMA",
//     "PK": "PAK",
//     "PA": "PAN",
//     "PY": "PAR",
//     "PE": "PER",
//     "PH": "PHI",
//     "PS": "PLE",
//     "PW": "PLW",
//     "PG": "PNG",
//     "PL": "POL",
//     "PT": "POR",
//     "KP": "PRK",
//     "QA": "QAT",
//     "MH": "RMI",
//     "RO": "ROM",
//     "ZA": "RSA",
//     "RU": "RUS",
//     "RW": "RWA",
//     "WS": "SAM",
//     "RS": "SCG",
//     "SN": "SEN",
//     "SC": "SEY",
//     "SG": "SIN",
//     "KN": "SKN",
//     "SL": "SLE",
//     "SI": "SLO",
//     "SM": "SMR",
//     "SB": "SOL",
//     "SO": "SOM",
//     "LK": "SRI",
//     "ST": "STP",
//     "SD": "SUD",
//     "CH": "SUI",
//     "SR": "SUR",
//     "SK": "SVK",
//     "SZ": "SWZ",
//     "SE": "SWE",
//     "SY": "SYR",
//     "TZ": "TAN",
//     "TO": "TGA",
//     "TH": "THA",
//     "TJ": "TJK",
//     "TM": "TKM",
//     "TL": "TLS",
//     "TG": "TOG",
//     "TT": "TRI",
//     "TN": "TUN",
//     "TR": "TUR",
//     "TV": "TUV",
//     "AE": "UAE",
//     "UG": "UGA",
//     "UA": "UKR",
//     "UY": "URU",
//     "US": "USA",
//     "UZ": "UZB",
//     "VU": "VAN",
//     "VA": "VAT",
//     "VE": "VEN",
//     "VN": "VIE",
//     "VC": "VIN",
//     "YE": "YEM",
//     "ZM": "ZAM",
//     "ZW": "ZIM"
// };


// export let nameToCode = {
//     'Afghanistan': 'AFG',
//     'Angola': 'AGO',
//     'Albania': 'ALB',
//     'United Arab Emirates': 'ARE',
//     'Argentina': 'ARG',
//     'Armenia': 'ARM',
//     'French Southern and Antarctic Lands': 'ATF',
//     'Australia': 'AUS',
//     'Austria': 'AUT',
//     'Azerbaijan': 'AZE',
//     'Burundi': 'BDI',
//     'Belgium': 'BEL',
//     'Benin': 'BEN',
//     'Burkina Faso': 'BFA',
//     'Bangladesh': 'BGD',
//     'Bulgaria': 'BGR',
//     'The Bahamas': 'BHS',
//     'Bosnia and Herzegovina': 'BIH',
//     'Belarus': 'BLR',
//     'Belize': 'BLZ',
//     'Bermuda': 'BMU',
//     'Bolivia': 'BOL',
//     'Brazil': 'BRA',
//     'Brunei': 'BRN',
//     'Bhutan': 'BTN',
//     'Botswana': 'BWA',
//     'Central African Republic': 'CAF',
//     'Canada': 'CAN',
//     'Switzerland': 'CHE',
//     'Chile': 'CHL',
//     'China': 'CHN',
//     'Ivory Coast': 'CIV',
//     'Cameroon': 'CMR',
//     'Democratic Republic of the Congo': 'COD',
//     'Republic of the Congo': 'COG',
//     'Colombia': 'COL',
//     'Costa Rica': 'CRI',
//     'Cuba': 'CUB',
//     'Northern Cyprus': 'CYP',
//     'Cyprus': 'CYP',
//     'Czech Republic': 'CZE',
//     'Germany': 'DEU',
//     'Djibouti': 'DJI',
//     'Denmark': 'DNK',
//     'Dominican Republic': 'DOM',
//     'Algeria': 'DZA',
//     'Ecuador': 'ECU',
//     'Egypt': 'EGY',
//     'Eritrea': 'ERI',
//     'Spain': 'ESP',
//     'Estonia': 'EST',
//     'Ethiopia': 'ETH',
//     'Finland': 'FIN',
//     'Fiji': 'FJI',
//     'Falkland Islands': 'FLK',
//     'France': 'FRA',
//     'Gabon': 'GAB',
//     'United Kingdom': 'GBR',
//     'Georgia': 'GEO',
//     'Ghana': 'GHA',
//     'Guinea': 'GIN',
//     'Gambia': 'GMB',
//     'Guinea Bissau': 'GNB',
//     'Equatorial Guinea': 'GNQ',
//     'Greece': 'GRC',
//     'Greenland': 'GRL',
//     'Guatemala': 'GTM',
//     'French Guiana': 'GUF',
//     'Guyana': 'GUY',
//     'Honduras': 'HND',
//     'Croatia': 'HRV',
//     'Haiti': 'HTI',
//     'Hungary': 'HUN',
//     'Indonesia': 'INA',
//     'India': 'IND',
//     'Ireland': 'IRL',
//     'Iran': 'IRN',
//     'Iraq': 'IRQ',
//     'Iceland': 'ISL',
//     'Israel': 'ISR',
//     'Italy': 'ITA',
//     'Jamaica': 'JAM',
//     'Jordan': 'JOR',
//     'Japan': 'JPN',
//     'Kazakhstan': 'KAZ',
//     'Kenya': 'KEN',
//     'Kyrgyzstan': 'KGZ',
//     'Cambodia': 'KHM',
//     'South Korea': 'KOR',
//     'Kosovo': false,
//     'Kuwait': 'KWT',
//     'Laos': 'LAO',
//     'Lebanon': 'LBN',
//     'Liberia': 'LBR',
//     'Libya': 'LBY',
//     'Sri Lanka': 'LKA',
//     'Lesotho': 'LSO',
//     'Lithuania': 'LTU',
//     'Luxembourg': 'LUX',
//     'Latvia': 'LVA',
//     'Morocco': 'MAR',
//     'Moldova': 'MDA',
//     'Madagascar': 'MDG',
//     'Mexico': 'MEX',
//     'Macedonia': 'MKD',
//     'Mali': 'MLI',
//     'Myanmar': 'MMR',
//     'Montenegro': 'MNE',
//     'Mongolia': 'MNG',
//     'Mozambique': 'MOZ',
//     'Mauritania': 'MRT',
//     'Malawi': 'MWI',
//     'Malaysia': 'MYS',
//     'Namibia': 'NAM',
//     'New Caledonia': 'NCL',
//     'Niger': 'NER',
//     'Nigeria': 'NGA',
//     'Nicaragua': 'NIC',
//     'Netherlands': 'NLD',
//     'Norway': 'NOR',
//     'Nepal': 'NPL',
//     'New Zealand': 'NZL',
//     'Oman': 'OMN',
//     'Pakistan': 'PAK',
//     'Panama': 'PAN',
//     'Peru': 'PER',
//     'Philippines': 'PHL',
//     'Papua New Guinea': 'PNG',
//     'Poland': 'POL',
//     'Puerto Rico': 'PRI',
//     'North Korea': 'PRK',
//     'Portugal': 'PRT',
//     'Paraguay': 'PRY',
//     'Qatar': 'QAT',
//     'Romania': 'ROU',
//     'Russia': 'RUS',
//     'Rwanda': 'RWA',
//     'Western Sahara': 'ESH',
//     'Saudi Arabia': 'SAU',
//     'Sudan': 'SDN',
//     'South Sudan': 'SSD',
//     'Senegal': 'SEN',
//     'Solomon Islands': 'SLB',
//     'Sierra Leone': 'SLE',
//     'El Salvador': 'SLV',
//     'Somaliland': false,
//     'Somalia': 'SOM',
//     'Republic of Serbia': 'SRB',
//     'Suriname': 'SUR',
//     'Slovakia': 'SVK',
//     'Slovenia': 'SVN',
//     'Sweden': 'SWE',
//     'Swaziland': 'SWZ',
//     'Syria': 'SYR',
//     'Chad': 'TCD',
//     'Togo': 'TGO',
//     'Thailand': 'THA',
//     'Tajikistan': 'TJK',
//     'Turkmenistan': 'TKM',
//     'East Timor': 'TLS',
//     'Trinidad and Tobago': 'TTO',
//     'Tunisia': 'TUN',
//     'Turkey': 'TUR',
//     'United Republic of Tanzania': 'TZA',
//     'Uganda': 'UGA',
//     'Ukraine': 'UKR',
//     'Uruguay': 'URY',
//     'United States of America': 'USA',
//     'Uzbekistan': 'UZB',
//     'Venezuela': 'VEN',
//     'Vietnam': 'VNM',
//     'Vanuatu': 'VUT',
//     'West Bank': false,
//     'Yemen': 'YEM',
//     'South Africa': 'ZAF',
//     'Zambia': 'ZMB',
//     'Zimbabwe': 'ZWE'
// };

// export let codeToName = _flipObject(nameToCode);
// export let tw = _flipObject(__tw);

export let offsetMapData = {
        'Canada':true,
        'United States of America':true,
        'Mexico':true,
        'Cuba':true,
        'The Bahamas':true,
        'Dominican Republic':true,
        'Haiti':true,
        'Honduras':true,
        'El Salvador':true,
        'Belize':true,
        'Guatemala':true,
        'Jamaica':true,
        'Nicaragua':true,
        'Costa Rica':true,
        'Panama':true,
        'Colombia':true,
        'Venezuela':true,
        'Trinidad and Tobago':true,
        'Guyana':true,
        'French Guiana':true,
        // 'Fiji':true,
        'Suriname':true,
        'Ecuador':true,
        'Peru':true,
        'Bolivia':true,
        'Bermuda':true,
        'Brazil':true,
        'Paraguay':true,
        'Chile':true,
        'Argentina':true,
        'Uruguay':true,
        'United Kingdom Falkland Islands1':true,
        'United Kingdom Falkland Islands2':true,
        'Falkland Islands':true,
        'Russia - USA':true,
        'Greenland':true,
        'Puerto Rico':true
};



export let GEO = [['YK','CS-KM','Kosovo'],['XS','SXM','Somaliland'],["AD","AND","Andorra"],["AE","ARE","United Arab Emirates"],["AF","AFG","Afghanistan"],["AG","ATG","Antigua & Barbuda"],["AI","AIA","Anguilla"],["AL","ALB","Albania"],["AM","ARM","Armenia"],["AO","AGO","Angola"],["AQ","ATA","Antarctica"],['CY','CYP','Cyprus'],["AR","ARG","Argentina"],["AS","ASM","American Samoa"],["AT","AUT","Austria"],["AU","AUS","Australia"],["AW","ABW","Aruba"],["AX","ALA","?aland Island"],["AZ","AZE","Azerbaijan"],["BA","BIH","Bosnia and Herzegovina"],["BB","BRB","Barbados"],["BD","BGD","Bangladesh"],["BE","BEL","Belgium"],["BF","BFA","Burkina Faso"],["BG","BGR","Bulgaria"],["BH","BHR","Bahrain"],["BI","BDI","Burundi"],["BJ","BEN","Benin"],["BL","BLM","Saint Barthélemy"],["BM","BMU","Bermuda"],["BN","BRN","Brunei"],["BO","BOL","Bolivia"],["BQ","BES","Caribbean Netherlands"],["BR","BRA","Brazil"],["BS","BHS","The Bahamas"],["BT","BTN","Bhutan"],["BV","BVT","Bouvet Island"],["BW","BWA","Botswana"],["BY","BLR","Belarus"],["BZ","BLZ","Belize"],["CA","CAN","Canada"],["CC","CCK","Cocos (Keeling) Islands"],["CF","CAF","Central African Republic"],["CH","CHE","Switzerland"],["CL","CHL","Chile"],["CM","CMR","Cameroon"],["CO","COL","Colombia"],["CR","CRI","Costa Rica"],["CU","CUB","Cuba"],["CV","CPV","Cape Verde"],["CX","CXR","Christmas Island"],["NCY","NCYP","Northern Cyprus"],["CZ","CZE","Czech Republic"],["DE","DEU","Germany"],["DJ","DJI","Djibouti"],["DK","DNK","Denmark"],["DM","DMA","Dominica"],["DO","DOM","Dominican Republic"],["DZ","DZA","Algeria"],["EC","ECU","Ecuador"],["EE","EST","Estonia"],["EG","EGY","Egypt"],["EH","ESH","Western Sahara"],["ER","ERI","Eritrea"],["ES","ESP","Spain"],["FI","FIN","Finland"],["FJ","FJI","Fiji"],["FK","FLK","Falkland Islands"],["FM","FSM","Federated States of Micronesia"],["FO","FRO","Faroe Islands"],["FR","FRA","France"],["GA","GAB","Gabon"],["GD","GRD","Grenada"],["GE","GEO","Georgia"],["GF","GUF","French Guiana"],["GH","GHA","Ghana"],["GI","GIB","Gibraltar"],["GL","GRL","Greenland"],["GN","GIN","Guinea"],["GP","GLP","Guadeloupe"],["GQ","GNQ","Equatorial Guinea"],["GR","GRC","Greece"],["GS","SGS","South Georgia and the South Sandwich Islands"],["GT","GTM","Guatemala"],["GU","GUM","Guam"],["GW","GNB","Guinea Bissau"],["GY","GUY","Guyana"],["HK","HKG","Hong Kong"],["HM","HMD","Heard Island and McDonald Islands"],["HN","HND","Honduras"],["HR","HRV","Croatia"],["HT","HTI","Haiti"],["HU","HUN","Hungary"],["ID","IDN","Indonesia"],["IE","IRL","Ireland"],["IL","ISR","Israel"],["IM","IMN","Isle of Man"],["IN","IND","India"],["IO","IOT","British Indian Ocean Territory"],["IQ","IRQ","Iraq"],["IR","IRN","Iran"],["IS","ISL","Iceland"],["IT","ITA","Italy"],["JE","JEY","Jersey"],["JM","JAM","Jamaica"],["JO","JOR","Jordan"],["JP","JPN","Japan"],["KH","KHM","Cambodia"],["KI","KIR","Kiribati"],["KM","COM","The Comoros"],["KW","KWT","Kuwait"],["KY","CYM","Cayman Islands"],["LB","LBN","Lebanon"],["LI","LIE","Liechtenstein"],["LK","LKA","Sri Lanka"],["LR","LBR","Liberia"],["LS","LSO","Lesotho"],["LT","LTU","Lithuania"],["LU","LUX","Luxembourg"],["LV","LVA","Latvia"],["LY","LBY","Libya"],["MA","MAR","Morocco"],["MC","MCO","Monaco"],["MD","MDA","Moldova"],["ME","MNE","Montenegro"],["MF","MAF","Saint Martin (France)"],["MG","MDG","Madagascar"],["MH","MHL","Marshall islands"],["MK","MKD","Macedonia"],["ML","MLI","Mali"],["MM","MMR","Myanmar"],["MO","MAC","Macao"],["MQ","MTQ","Martinique"],["MR","MRT","Mauritania"],["MS","MSR","Montserrat"],["MT","MLT","Malta"],["MV","MDV","Maldives"],["MW","MWI","Malawi"],["MX","MEX","Mexico"],["MY","MYS","Malaysia"],["NA","NAM","Namibia"],["NE","NER","Niger"],["NF","NFK","Norfolk Island"],["NG","NGA","Nigeria"],["NI","NIC","Nicaragua"],["NL","NLD","Netherlands"],["NO","NOR","Norway"],["NP","NPL","Nepal"],["NR","NRU","Nauru"],["OM","OMN","Oman"],["PA","PAN","Panama"],["PE","PER","Peru"],["PF","PYF","French polynesia"],["PG","PNG","Papua New Guinea"],["PH","PHL","Philippines"],["PK","PAK","Pakistan"],["PL","POL","Poland"],["PN","PCN","Pitcairn Islands"],["PR","PRI","Puerto Rico"],["PS","PSE","West Bank"],["PW","PLW","Palau"],["PY","PRY","Paraguay"],["QA","QAT","Qatar"],["RE","REU","Réunion"],["RO","ROU","Romania"],["RS","SRB","Republic of Serbia"],["RU","RUS","Russia"],["RW","RWA","Rwanda"],["SB","SLB","Solomon Islands"],["SC","SYC","Seychelles"],["SD","SDN","Sudan"],["SE","SWE","Sweden"],["SG","SGP","Singapore"],["SI","SVN","Slovenia"],["SJ","SJM","Template:Country data SJM Svalbard"],["SK","SVK","Slovakia"],["SL","SLE","Sierra Leone"],["SM","SMR","San Marino"],["SN","SEN","Senegal"],["SO","SOM","Somalia"],["SR","SUR","Suriname"],["SS","SDS","South Sudan"],["ST","STP","Sao Tome & Principe"],["SV","SLV","El Salvador"],["SY","SYR","Syria"],["SZ","SWZ","Swaziland"],["TC","TCA","Turks & Caicos Islands"],["TD","TCD","Chad"],["TG","TGO","Togo"],["TH","THA","Thailand"],["TK","TKL","Tokelau"],["TL","TLS","East Timor"],["TN","TUN","Tunisia"],["TO","TON","Tonga"],["TR","TUR","Turkey"],["TV","TUV","Tuvalu"],["TZ","TZA","United Republic of Tanzania"],["UA","UKR","Ukraine"],["UG","UGA","Uganda"],["US","USA","United States of America"],["UY","URY","Uruguay"],["VA","VAT","Vatican City (The Holy See)"],["VE","VEN","Venezuela"],["VG","VGB","British Virgin Islands"],["VI","VIR","United States Virgin Islands"],["VN","VNM","Vietnam"],["WF","WLF","Wallis and Futuna"],["WS","WSM","Samoa"],["YE","YEM","Yemen"],["YT","MYT","Mayotte"],["ZA","ZAF","South Africa"],["ZM","ZMB","Zambia"],["ZW","ZWE","Zimbabwe"],["CN","CHN","China"],["CG","COG","Republic of the Congo"],["CD","COD","Democratic Republic of the Congo"],["MZ","MOZ","Mozambique"],["GG","GGY","Guernsey"],["GM","GMB","Gambia"],["MP","MNP","Northern Mariana Islands"],["ET","ETH","Ethiopia"],["NC","NCL","New Caledonia"],["VU","VUT","Vanuatu"],["TF","ATF","French Southern and Antarctic Lands"],["NU","NIU","Niue"],["UM","UMI","United States Minor Outlying Islands"],["CK","COK","Cook Islands"],["GB","GBR","United Kingdom"],["TT","TTO","Trinidad and Tobago"],["VC","VCT","St. Vincent & the Grenadines"],["TW","TWN","Taiwan"],["NZ","NZL","New Zealand"],["SA","SAU","Saudi Arabia"],["LA","LAO","Laos"],["KP","PRK","North Korea"],["KR","KOR","South Korea"],["PT","PRT","Portugal"],["KG","KGZ","Kyrgyzstan"],["KZ","KAZ","Kazakhstan"],["TJ","TJK","Tajikistan"],["TM","TKM","Turkmenistan"],["UZ","UZB","Uzbekistan"],["KN","KNA","St. Kitts & Nevis"],["PM","SPM","Saint-Pierre and Miquelon"],["SH","SHN","St. Helena & Dependencies"],["LC","LCA","St. Lucia"],["MU","MUS","Mauritius"],["CI","CIV","Ivory Coast"],["KE","KEN","Kenya"],["MN","MNG","Mongolia"]];

let NAME_TO_CODE=[],__TW=[];

GEO.map(e=>{
  NAME_TO_CODE.push([e[2],e[1]]);
  __TW.push([e[0],e[1]])
})

export let nameToCode = _fromPairs(NAME_TO_CODE);
export let codeToName = _flipObject(nameToCode);
export let __tw = _fromPairs(__TW);
export let tw = _flipObject(__tw);
